// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZiDD867cFIki7Vwrjmo-8a_S_bp2jPk',
    appId: '1:964528386590:web:5c42d848d1d13c7127340f',
    messagingSenderId: '964528386590',
    projectId: 'contol-regional-officer',
    authDomain: 'contol-regional-officer.firebaseapp.com',
    storageBucket: 'contol-regional-officer.firebasestorage.app',
    measurementId: 'G-WFPFGVPTZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVTvrYEfVDRxq3JgUxSUbFctr-jva_sc',
    appId: '1:964528386590:android:46dc3dddb9b62fff27340f',
    messagingSenderId: '964528386590',
    projectId: 'contol-regional-officer',
    storageBucket: 'contol-regional-officer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJgK-RnehxH02vf6ILKsvifADkdKS04I',
    appId: '1:964528386590:ios:5cdee37b90e488bc27340f',
    messagingSenderId: '964528386590',
    projectId: 'contol-regional-officer',
    storageBucket: 'contol-regional-officer.firebasestorage.app',
    iosBundleId: 'com.example.contolOfficerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnJgK-RnehxH02vf6ILKsvifADkdKS04I',
    appId: '1:964528386590:ios:5cdee37b90e488bc27340f',
    messagingSenderId: '964528386590',
    projectId: 'contol-regional-officer',
    storageBucket: 'contol-regional-officer.firebasestorage.app',
    iosBundleId: 'com.example.contolOfficerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIZiDD867cFIki7Vwrjmo-8a_S_bp2jPk',
    appId: '1:964528386590:web:6a8a779a0e16298927340f',
    messagingSenderId: '964528386590',
    projectId: 'contol-regional-officer',
    authDomain: 'contol-regional-officer.firebaseapp.com',
    storageBucket: 'contol-regional-officer.firebasestorage.app',
    measurementId: 'G-1C5W64R15R',
  );
}
